### PR TITLE
Document Kokkos_ENABLE_SIMD_NATIVE

### PR DESCRIPTION
**Pull request by masterleinad**
Corresponds to https://github.com/kokkos/kokkos/pull/6188.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
Plz make it a draft to make sure we don't accidentally merge before the changes are merged into Kokkos Core

**Comment by masterleinad** [comment]
> Plz make it a draft to make sure we don't accidentally merge before the changes are merged into Kokkos Core

Sure.

**Comment by ldh4** [comment]
Just double checking, isn't this related to https://github.com/kokkos/kokkos/pull/6188 instead?

**Comment by masterleinad** [comment]
> Just double checking, isn't this related to [kokkos/kokkos#6188](https://github.com/kokkos/kokkos/pull/6188) instead?

Yes, fixed.

**Comment by Yaraslaut** [comment]
https://github.com/kokkos/kokkos/pull/6188 is merged

**Pull request closed without merging**
