### PR TITLE
#120: API-core-c_style_memory_management-realloc from md to rst

### PR DESCRIPTION
**Pull request by antoinemeyer5**
### THIS PR:
* API/core/c_style_memory_management/realloc transition from .md to .rst

before (.md) | after (.rst)
:----------------: | :-------------:
image | image

### CODE REVIEW

**Review by fnrizzi — APPROVED** [review]

**Review by fnrizzi — CHANGES_REQUESTED** [review]
you should use cppkokkos:function here and docuemnt things accordingly

**Comment by antoinemeyer5** [comment]
> you should use cppkokkos:function here and docuemnt things accordingly

1. use cppkokkos:function: OK
2. document things accordingly: can you give me more information?

**Comment by fnrizzi** [comment]
> > you should use cppkokkos:function here and docuemnt things accordingly
> 
> 1. use cppkokkos:function: OK
> 2. document things accordingly: can you give me more information?

what i meant was to consistently use the sphinx cppkokkos format, and only use code blocks if no alternative is avialable

**Comment by antoinemeyer5** [comment]
> > > you should use cppkokkos:function here and docuemnt things accordingly
> > 
> > 
> > 
> > 1. use cppkokkos:function: OK
> > 2. document things accordingly: can you give me more information?
> 
> what i meant was to consistently use the sphinx cppkokkos format, and only use code blocks if no alternative is avialable

Oh ok it's noted
Be careful, I see the new screenshot but not the code (you have to push on my branch)

**Review by fnrizzi — APPROVED** [review]

**Pull request merged**
