### PR TITLE
WIP #34: Update packages to the latest versions and check the docs structure

### LINKED ISSUE #34: Update packages to the latest versions and fix Programming guide
### TODO:
- update Python packages
- add .gitignore file
- check documentation structure for:
  - missing pages/blocks
  - obvious mistakes

### PR DESCRIPTION
**Pull request by marcinwrobel1986**
THIS PR (Programming Guide):
- added `.gitignore` file
- added `requirements.txt` file for Python dependencies (removed from README.md file)
- added `ScatterView` to `API/containers`
- changed order in `API/core` (first functions, then alphabetical order)
- fixed headings and grammar in `API/core/Task-Parallelism` (previously incorrect rendering)
- changed order in `API/core/atomics` (to alphabetical order)
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_compare_exchange'
- removed unnecessary indentation in 'API/core/atomics/atomic_compare_exchange_strong'
- removed unnecessary indentation in 'API/core/atomics/atomic_exchange'
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_fetch_op'
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_load'
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_op'
- removed unnecessary indentation, dot and too many blank lines in 'API/core/atomics/atomic_op_fetch'
- removed unnecessary indentation and too many blank lines in 'API/core/atomics/atomic_store'
- reorganized `API/core/builtin_reducers`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/BAnd`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/BOr`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/LAnd`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/LOr`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/Max`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/MaxLoc`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/Min`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/MinLoc`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/MinMax`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/MinMaxLoc`
- added missing `API/core/builtinreducers/MinMaxLocScalar`
- added missing `API/core/builtinreducers/MinMaxScalar`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/Prod`
- added missing `API/core/builtinreducers/ReducerConcept`
- added missing `API/core/builtinreducers/ReductionScalarTypes`
- fixed links, removed unnecessary indentation, removed char "`" in order to render C++ block corectly in `API/core/builtinreducers/Sum`
- added missing `API/core/builtinreducers/ValLocScalar`
- fixed links and removed namespace in `API/core/fence`
- removed blank line and removed unnecessary indentation in `API/core/parallel_for`
- fixed link, removed one which directed to `TBD`, added links to other `atomic_ops`, reorganized table alphabetically like order in the tree, removed blank lines, fixed grammar in `ProgrammingGuide/Atomic-Operations`
- fixed grammar, added links and removed unnecessary char "`" in code blocks in `ProgrammingGuide/Compiling`
- convert file from `.md` to `.rst` in order to add tree and links in `ProgrammingGuide/Custom-Reductions`
- added missing `ProgrammingGuide/Custom-Reductions:-Built-In-Reducers-with-Custom-Scalar-Types`
- added missing `ProgrammingGuide/Custom-Reductions:-Built-In-Reducers`
- added missing `ProgrammingGuide/Custom-Reductions:-Custom-Reducers`
- added links, removed dot, fixed grammar, removed unnecessary indentation in `ProgrammingGuide/HierarchicalParallelism`
- removed blank line, fixed headings and added links in `ProgrammingGuide/Initialization`
- removed blank line, added links, removed unnecessary indentation and fixed grammar in `ProgrammingGuide/Interoperability`
- removed blank line, fixed grammar and added links in `ProgrammingGuide/Introduction`
- fixed formatting, removed blank lines, fixed pics rendering and fixed links `ProgrammingGuide/Kokkos-and-Virtual-Functions`
- removed spaces and blank lines, added links, fixed grammar in `ProgrammingGuide/Machine-Model`
- added links, removed unnecessary indentation and fixed grammar in `ProgrammingGuide/ParallelDispatch`
- added links in `ProgrammingGuide/ProgrammingModel`
- added links and removed unnecessary indentation in `ProgrammingGuide/Subviews.md`
- added links and fixed grammar in `ProgrammingGuide/View`
- changed hardcoded date to current year, removed not needed slashes and added `myst_heading_anchors` parameter in Sphinx config file `conf.py`
- fixed links in `index.rst`
- removed unnecessary data from `programmingguide`
- fixed link in `testing-and-issue-tracking/Requirements-Issues-and-Feedback`
- fixed link in `usecases/VirtualFunctions`

Closes #34 

[docs_PR_36.zip](https://github.com/kokkos/kokkos-core-wiki/files/8880393/docs_PR_36.zip)

### CODE REVIEW

**Comment by fnrizzi** [comment]
if this PR is about programming guide why there are so many other files updated?

**Comment by marcinwrobel1986** [comment]
> if this PR is about programming guide why there are so many other files updated? @marcinwrobel1986

I fixed the files which were in links from Programming Guide pages

**Comment by fnrizzi** [comment]
can we put also a preview of what the website looks like? if you add a zip here with the html built so I can see

**Comment by fnrizzi** [comment]
ops! I did not see the draft , i thought it was ready for review

**Comment by fnrizzi** [comment]
converting this to draft so that it is clear it is not a valid PR

**Comment by marcinwrobel1986** [comment]
Was splitted into smaller PR and merged.

**Pull request closed without merging**
