### PR TITLE
#120: API-containers-DualView from md to rst

### PR DESCRIPTION
**Pull request by antoinemeyer5**
### THIS PR:
* API/containers/DualView transition from .md to .rst

before (.md) | after (.rst)
:----------------: | :-------------:
image |  image
image | image
image | image
image | image
image | image

### CODE REVIEW

**Review by fnrizzi — CHANGES_REQUESTED** [review]
this needs to be converted to sphinx , drop the synopsis please. use all comments as descriptions of sphinx functions. etc

**Comment by antoinemeyer5** [comment]
> this needs to be converted to sphinx , drop the synopsis please. use all comments as descriptions of sphinx functions. etc

Hello FR,

here are some screenshots to show the beginning of the new render requested.

image

image

image

For the moment I left the Synopsis at the bottom. The lines with [X] at the beginning have already been processed.

Also I have 2 problems: 

- to use Sphinx you often have to simplify the lines. For example in Typedefs, go from
`typedef ViewTraits<DataType, Arg1Type, Arg2Type, Arg3Type> traits;`
to
`traits`
That makes lose a lot of information, no? Should I continue like this?

- Some lines are strange for me. How should I handle them? Example, line 171 to 182.

image

**Review by tcclevenger — APPROVED** [review]
Is the alignment of code blocks in our control? For example, in the class description
Old:
Screenshot 2023-03-08 at 11 01 56 AM
New:
Screenshot 2023-03-08 at 11 01 28 AM
The old looks nicer in my opinion, whereas the new is less neat with the `= void>` hanging and the `class DualView` indented.

Just curious, wording is fine so I'll approve.

**Comment by fnrizzi** [comment]
@tcclevenger found it: https://github.com/sphinx-doc/sphinx/pull/11011
but it is literally in progress so we have to wait !

**Review by fnrizzi — APPROVED** [review]

**Pull request merged**
